object FrmAdminAccount: TFrmAdminAccount
  Left = 0
  Top = 0
  Caption = 'FrmAdminAccount'
  ClientHeight = 470
  ClientWidth = 850
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object ImgAccount: TImage
    Left = 654
    Top = 47
    Width = 137
    Height = 80
  end
  object LblName: TLabel
    Left = 283
    Top = 144
    Width = 53
    Height = 19
    Caption = 'Name:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object LblSurname: TLabel
    Left = 258
    Top = 177
    Width = 78
    Height = 19
    Caption = 'Surname:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object LblEmail: TLabel
    Left = 284
    Top = 245
    Width = 51
    Height = 19
    Caption = 'Email:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object LblAdminID: TLabel
    Left = 267
    Top = 215
    Width = 82
    Height = 19
    Caption = 'Admin ID:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object LblPassword: TLabel
    Left = 253
    Top = 311
    Width = 84
    Height = 19
    Caption = 'Password:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object LblCellNum: TLabel
    Left = 231
    Top = 278
    Width = 106
    Height = 19
    Caption = 'Cell Number:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    ParentShowHint = False
    ShowHint = False
  end
  object LblAccount: TLabel
    Left = 152
    Top = 16
    Width = 473
    Height = 45
    Caption = 'ACCOUNT INFORMATION'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -37
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object LblTime: TLabel
    Left = 8
    Top = 8
    Width = 46
    Height = 14
    Caption = 'LblTime'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
  end
  object BtnDone: TButton
    Left = 564
    Top = 240
    Width = 227
    Height = 45
    Caption = 'DONE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 0
    OnClick = BtnDoneClick
  end
  object BtnUndo: TButton
    Left = 564
    Top = 188
    Width = 227
    Height = 46
    Caption = 'UNDO'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
    OnClick = BtnUndoClick
  end
  object BtnEdit: TButton
    Left = 564
    Top = 136
    Width = 227
    Height = 46
    Caption = 'EDIT'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    OnClick = BtnEditClick
  end
  object EdtName: TEdit
    Left = 342
    Top = 141
    Width = 175
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 3
    Text = 'EdtName'
  end
  object EdtSurname: TEdit
    Left = 342
    Top = 174
    Width = 175
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 4
    Text = 'EdtSurname'
  end
  object EdtEmail: TEdit
    Left = 341
    Top = 242
    Width = 175
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
    Text = 'EdtEmail'
  end
  object EdtCellNumber: TEdit
    Left = 343
    Top = 275
    Width = 175
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
    Text = 'EdtCellNumber'
  end
  object EdtPassword: TEdit
    Left = 343
    Top = 308
    Width = 175
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    PasswordChar = '*'
    TabOrder = 7
    Text = 'EdtPassword'
  end
  object EdtAdminID: TEdit
    Left = 341
    Top = 209
    Width = 175
    Height = 27
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
    Text = 'EdtAdminID'
  end
  object BtnHelp: TButton
    Left = 770
    Top = 8
    Width = 33
    Height = 33
    Caption = '?'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 9
    OnClick = BtnHelpClick
  end
  object BtnClose: TButton
    Left = 809
    Top = 8
    Width = 33
    Height = 33
    Caption = 'X'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 10
    OnClick = BtnCloseClick
  end
  object BtnBack: TButton
    Left = 8
    Top = 419
    Width = 89
    Height = 33
    Caption = 'Back'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 11
    OnClick = BtnBackClick
  end
  object BtnDelete: TButton
    Left = 564
    Top = 291
    Width = 227
    Height = 46
    Caption = 'DELETE'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 12
    OnClick = BtnDeleteClick
  end
  object ChkShow: TCheckBox
    Left = 343
    Top = 336
    Width = 97
    Height = 14
    Caption = 'Show Password'
    TabOrder = 13
    OnClick = ChkShowClick
  end
  object BtnLogOut: TButton
    Left = 22
    Top = 157
    Width = 171
    Height = 39
    Caption = 'LOG OUT'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -21
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 14
    OnClick = BtnLogOutClick
  end
  object TTimeCentre: TTimer
    Interval = 1
    Left = 72
    Top = 72
  end
  object TTime: TTimer
    Left = 24
    Top = 72
  end
end
